#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-cssparser
Version  : 1
Release  : 1
URL      : https://sourceforge.net/projects/cssparser/files/cssparser/0.9.16/cssparser-0.9.16-sources.jar
Source0  : https://sourceforge.net/projects/cssparser/files/cssparser/0.9.16/cssparser-0.9.16-sources.jar
Source1  : https://repo1.maven.org/maven2/net/sourceforge/cssparser/cssparser/0.9.16/cssparser-0.9.16.jar
Source2  : https://repo1.maven.org/maven2/net/sourceforge/cssparser/cssparser/0.9.16/cssparser-0.9.16.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: mvn-cssparser-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-cssparser package.
Group: Data

%description data
data components for the mvn-cssparser package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/cssparser/cssparser/0.9.16
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/cssparser/cssparser/0.9.16

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/cssparser/cssparser/0.9.16
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/cssparser/cssparser/0.9.16


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/sourceforge/cssparser/cssparser/0.9.16/cssparser-0.9.16.jar
/usr/share/java/.m2/repository/net/sourceforge/cssparser/cssparser/0.9.16/cssparser-0.9.16.pom
